### ISSUE TITLE
运行node run.js报错

### ISSUE THREAD

**Issue by Cheng007** [Lxxyx/koa2-easy#7]
如题，用koa2-easy生成了 js 版的项目，安装好后运行 node run.js 报如下错：
```dash
   D:\koa\koa2-easy-js\node_modules\.4.1.0@koa-send\index.js:37
async function send (ctx, path, opts = {}) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\koa\koa2-easy-js\node_modules\.6.24.1@babel-register\lib\
node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:/koa/koa2-easy-js/app.js:5:1)
    at Module._compile (module.js:570:32)
    at loader (D:\koa\koa2-easy-js\node_modules\.6.24.1@babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\koa\koa2-easy-js\node_modules\.6.24.1@babel-register\lib\
node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
请问怎么解决？
谢谢

**Comment by Lxxyx** [comment]
![image](https://cloud.githubusercontent.com/assets/13161470/26538311/78662768-4478-11e7-9603-af44d3d7357d.png)
没有遇到类似问题，你的Node版本和koa2-easy版本是？
或者试试安装 koa2-easy最新版，npm i koa2-easy@latest -g
